title: 
  name: Bitácora de Pablo Rodríguez
  website: http://bitacora.pablo-rodriguez.tk
description: Pensamientos ocasionales
author:
  name: Pablo Rodríguez
  website: http://www.pablo-rodriguez.tk
lang: es
theme: minima
